//This file was generated by the LASAL2 CodeGenerator  -- 
//Please, do not edit this file (it might be overwritten by the next generator run)
typedef struct SvrCh_DINT 
  {
    CHMETH *pMeth;
    DINT dData;
    SVRDSC *pDsc;
  } SvrCh_DINT;

typedef struct CltCh_DINT 
  {
    struct SvrCh_DINT *pCh;
    DINT dData;
    SVRCHCMD *pCmd;
  } CltCh_DINT;

typedef struct SvrCh_FeSetup 
  {
    CHMETH *pMeth;
    FeSetup dData;
    SVRDSC *pDsc;
  } SvrCh_FeSetup;

typedef struct CltCh_FeSetup 
  {
    struct SvrCh_FeSetup *pCh;
    FeSetup dData;
    SVRCHCMD *pCmd;
  } CltCh_FeSetup;

typedef struct SvrCh_HDINT 
  {
    CHMETH *pMeth;
    HDINT dData;
    SVRDSC *pDsc;
  } SvrCh_HDINT;

typedef struct CltCh_HDINT 
  {
    struct SvrCh_HDINT *pCh;
    HDINT dData;
    SVRCHCMD *pCmd;
  } CltCh_HDINT;

typedef struct SvrCh_IO_State 
  {
    CHMETH *pMeth;
    IO_State dData;
    SVRDSC *pDsc;
  } SvrCh_IO_State;

typedef struct CltCh_IO_State 
  {
    struct SvrCh_IO_State *pCh;
    IO_State dData;
    SVRCHCMD *pCmd;
  } CltCh_IO_State;

typedef struct SvrCh_pVoid 
  {
    CHMETH *pMeth;
    pVoid dData;
    SVRDSC *pDsc;
  } SvrCh_pVoid;

typedef struct CltCh_pVoid 
  {
    struct SvrCh_pVoid *pCh;
    pVoid dData;
    SVRCHCMD *pCmd;
  } CltCh_pVoid;

typedef struct SvrCh_t_SDCIPortMode_PTofCls_SdiasSDCIMaster 
  {
    CHMETH *pMeth;
    t_SDCIPortMode dData;
    SVRDSC *pDsc;
  } SvrCh_t_SDCIPortMode_PTofCls_SdiasSDCIMaster;

typedef struct CltCh_t_SDCIPortMode_PTofCls_SdiasSDCIMaster 
  {
    struct SvrCh_t_SDCIPortMode_PTofCls_SdiasSDCIMaster *pCh;
    t_SDCIPortMode dData;
    SVRCHCMD *pCmd;
  } CltCh_t_SDCIPortMode_PTofCls_SdiasSDCIMaster;

typedef struct SvrCh_UDINT 
  {
    CHMETH *pMeth;
    UDINT dData;
    SVRDSC *pDsc;
  } SvrCh_UDINT;

typedef struct CltCh_UDINT 
  {
    struct SvrCh_UDINT *pCh;
    UDINT dData;
    SVRCHCMD *pCmd;
  } CltCh_UDINT;

typedef struct SvrChCmd_DINT 
  {
    CMDMETH *pMeth;
    DINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_DINT;

typedef struct CltChCmd__Can 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _Can *pCmd;
  } CltChCmd__Can;

typedef struct CltChCmd__CanLib 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _CanLib *pCmd;
  } CltChCmd__CanLib;

typedef struct CltChCmd__FileSys 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _FileSys *pCmd;
  } CltChCmd__FileSys;

typedef struct CltChCmd__Lse 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _Lse *pCmd;
  } CltChCmd__Lse;

typedef struct CltChCmd__MultiTask 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _MultiTask *pCmd;
  } CltChCmd__MultiTask;

typedef struct CltChCmd__OSKernel 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _OSKernel *pCmd;
  } CltChCmd__OSKernel;

typedef struct CltChCmd__OsziLSEBackground 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _OsziLSEBackground *pCmd;
  } CltChCmd__OsziLSEBackground;

typedef struct CltChCmd__SerLib 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _SerLib *pCmd;
  } CltChCmd__SerLib;

typedef struct CltChCmd__StdLib 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _StdLib *pCmd;
  } CltChCmd__StdLib;

typedef struct CltChCmd__TaskObjectControl 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    _TaskObjectControl *pCmd;
  } CltChCmd__TaskObjectControl;

typedef struct CltChCmd_ASCII_BIN 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    ASCII_BIN *pCmd;
  } CltChCmd_ASCII_BIN;

typedef struct SvrChCmd_UDINT 
  {
    CMDMETH *pMeth;
    UDINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_UDINT;

typedef struct CltChCmd_CriticalSection 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    CriticalSection *pCmd;
  } CltChCmd_CriticalSection;

typedef struct CltChCmd_DataServiceClient 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    DataServiceClient *pCmd;
  } CltChCmd_DataServiceClient;

typedef struct CltChCmd_DiasMaster 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    DiasMaster *pCmd;
  } CltChCmd_DiasMaster;

typedef struct CltChCmd_DiasMasterC 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    DiasMasterC *pCmd;
  } CltChCmd_DiasMasterC;

typedef struct CltChCmd_DiasMasterPostScan 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    DiasMasterPostScan *pCmd;
  } CltChCmd_DiasMasterPostScan;

typedef struct CltChCmd_DINT 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SVRCHCMD *pCmd;
  } CltChCmd_DINT;

typedef struct CltChCmd_EEPROM 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    EEPROM *pCmd;
  } CltChCmd_EEPROM;

typedef struct CltChCmd_GetBroadCastData 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    GetBroadCastData *pCmd;
  } CltChCmd_GetBroadCastData;

typedef struct CltChCmd_Graphic 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Graphic *pCmd;
  } CltChCmd_Graphic;

typedef struct CltChCmd_HmiAsciiBuffer 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiAsciiBuffer *pCmd;
  } CltChCmd_HmiAsciiBuffer;

typedef struct CltChCmd_HmiCanSendReceive 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiCanSendReceive *pCmd;
  } CltChCmd_HmiCanSendReceive;

typedef struct CltChCmd_HmiChkBitList 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiChkBitList *pCmd;
  } CltChCmd_HmiChkBitList;

typedef struct CltChCmd_HmiColorMap 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiColorMap *pCmd;
  } CltChCmd_HmiColorMap;

typedef struct CltChCmd_HmiComPort 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiComPort *pCmd;
  } CltChCmd_HmiComPort;

typedef struct CltChCmd_HmiFile 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiFile *pCmd;
  } CltChCmd_HmiFile;

typedef struct CltChCmd_HmiFont35 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiFont35 *pCmd;
  } CltChCmd_HmiFont35;

typedef struct CltChCmd_HmiFontList 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiFontList *pCmd;
  } CltChCmd_HmiFontList;

typedef struct CltChCmd_HmiFunctionList 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiFunctionList *pCmd;
  } CltChCmd_HmiFunctionList;

typedef struct CltChCmd_HmiFunctionList35 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiFunctionList35 *pCmd;
  } CltChCmd_HmiFunctionList35;

typedef struct CltChCmd_HmiImage35 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiImage35 *pCmd;
  } CltChCmd_HmiImage35;

typedef struct CltChCmd_HmiImageList 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiImageList *pCmd;
  } CltChCmd_HmiImageList;

typedef struct CltChCmd_HmiMapFile 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiMapFile *pCmd;
  } CltChCmd_HmiMapFile;

typedef struct CltChCmd_HmiMemCircle 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiMemCircle *pCmd;
  } CltChCmd_HmiMemCircle;

typedef struct CltChCmd_HmiMemImage 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiMemImage *pCmd;
  } CltChCmd_HmiMemImage;

typedef struct CltChCmd_HmiMemIO 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiMemIO *pCmd;
  } CltChCmd_HmiMemIO;

typedef struct CltChCmd_HmiMemLine 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiMemLine *pCmd;
  } CltChCmd_HmiMemLine;

typedef struct CltChCmd_HmiMemRectangle 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiMemRectangle *pCmd;
  } CltChCmd_HmiMemRectangle;

typedef struct CltChCmd_HmiMemText 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiMemText *pCmd;
  } CltChCmd_HmiMemText;

typedef struct CltChCmd_HmiMemZorder 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiMemZorder *pCmd;
  } CltChCmd_HmiMemZorder;

typedef struct CltChCmd_HmiProject35 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiProject35 *pCmd;
  } CltChCmd_HmiProject35;

typedef struct CltChCmd_HmiProjectList 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiProjectList *pCmd;
  } CltChCmd_HmiProjectList;

typedef struct CltChCmd_HmiScreen 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiScreen *pCmd;
  } CltChCmd_HmiScreen;

typedef struct CltChCmd_HmiSetUpList 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiSetUpList *pCmd;
  } CltChCmd_HmiSetUpList;

typedef struct CltChCmd_HmiSetupList35 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiSetupList35 *pCmd;
  } CltChCmd_HmiSetupList35;

typedef struct CltChCmd_HmiShemeList 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiShemeList *pCmd;
  } CltChCmd_HmiShemeList;

typedef struct CltChCmd_HmiShemeList35 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiShemeList35 *pCmd;
  } CltChCmd_HmiShemeList35;

typedef struct CltChCmd_HmiStateBit35 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiStateBit35 *pCmd;
  } CltChCmd_HmiStateBit35;

typedef struct CltChCmd_HmiStrLib 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiStrLib *pCmd;
  } CltChCmd_HmiStrLib;

typedef struct CltChCmd_HmiT9Config35 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiT9Config35 *pCmd;
  } CltChCmd_HmiT9Config35;

typedef struct CltChCmd_HmiTextList 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiTextList *pCmd;
  } CltChCmd_HmiTextList;

typedef struct CltChCmd_HmiTextList35 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    HmiTextList35 *pCmd;
  } CltChCmd_HmiTextList35;

typedef struct CltChCmd_HmiTextList35Manager 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiTextList35Manager *pCmd;
  } CltChCmd_HmiTextList35Manager;

typedef struct CltChCmd_HmiUniBuffer 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiUniBuffer *pCmd;
  } CltChCmd_HmiUniBuffer;

typedef struct CltChCmd_HmiUnitList 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiUnitList *pCmd;
  } CltChCmd_HmiUnitList;

typedef struct CltChCmd_HmiUtils 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiUtils *pCmd;
  } CltChCmd_HmiUtils;

typedef struct CltChCmd_HmiVarInfoList 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiVarInfoList *pCmd;
  } CltChCmd_HmiVarInfoList;

typedef struct CltChCmd_HmiVarList 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiVarList *pCmd;
  } CltChCmd_HmiVarList;

typedef struct CltChCmd_HmiVarList35 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HmiVarList35 *pCmd;
  } CltChCmd_HmiVarList35;

typedef struct CltChCmd_Hub_Base 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Hub_Base *pCmd;
  } CltChCmd_Hub_Base;

typedef struct CltChCmd_Hub_Base_Root 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Hub_Base_Root *pCmd;
  } CltChCmd_Hub_Base_Root;

typedef struct CltChCmd_HwcLogging 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HwcLogging *pCmd;
  } CltChCmd_HwcLogging;

typedef struct CltChCmd_HwControl 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HwControl *pCmd;
  } CltChCmd_HwControl;

typedef struct CltChCmd_HwControlBase 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HwControlBase *pCmd;
  } CltChCmd_HwControlBase;

typedef struct CltChCmd_HWKVarSizeFIFO 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HWKVarSizeFIFO *pCmd;
  } CltChCmd_HWKVarSizeFIFO;

typedef struct CltChCmd_HWRtPostScan 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    HWRtPostScan *pCmd;
  } CltChCmd_HWRtPostScan;

typedef struct CltChCmd_I2CCDIAS 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    I2CCDIAS *pCmd;
  } CltChCmd_I2CCDIAS;

typedef struct CltChCmd_MerkerEx 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    MerkerEx *pCmd;
  } CltChCmd_MerkerEx;

typedef struct CltChCmd_Ram 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Ram *pCmd;
  } CltChCmd_Ram;

typedef struct CltChCmd_RamFile 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    RamFile *pCmd;
  } CltChCmd_RamFile;

typedef struct CltChCmd_SafetyManager 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SafetyManager *pCmd;
  } CltChCmd_SafetyManager;

typedef struct CltChCmd_SdiasHubBase 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SdiasHubBase *pCmd;
  } CltChCmd_SdiasHubBase;

typedef struct SvrChCmd_t_e_VaranErrors 
  {
    CMDMETH *pMeth;
    t_e_VaranErrors dData;
    SVRDSC *pDsc;
  } SvrChCmd_t_e_VaranErrors;

typedef struct CltChCmd_SdiasManager 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    SdiasManager *pCmd;
  } CltChCmd_SdiasManager;

typedef struct CltChCmd_SdiasSafetyManagerFSoE 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SdiasSafetyManagerFSoE *pCmd;
  } CltChCmd_SdiasSafetyManagerFSoE;

typedef struct CltChCmd_Sfc_Action_Base 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    Sfc_Action_Base *pCmd;
  } CltChCmd_Sfc_Action_Base;

typedef struct SvrChCmd_pVoid 
  {
    CMDMETH *pMeth;
    pVoid dData;
    SVRDSC *pDsc;
  } SvrChCmd_pVoid;

typedef struct CltChCmd_Sfc_ActionInvoker 
  {
    struct SvrChCmd_pVoid *pCh;
    pVoid dData;
    Sfc_ActionInvoker *pCmd;
  } CltChCmd_Sfc_ActionInvoker;

typedef struct CltChCmd_SFC_Sort 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SFC_Sort *pCmd;
  } CltChCmd_SFC_Sort;

typedef struct CltChCmd_Sfc_StepInvoker 
  {
    struct SvrChCmd_pVoid *pCh;
    pVoid dData;
    Sfc_StepInvoker *pCmd;
  } CltChCmd_Sfc_StepInvoker;

typedef struct CltChCmd_SfcClass_Action0 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SfcClass_Action0 *pCmd;
  } CltChCmd_SfcClass_Action0;

typedef struct CltChCmd_SfcClass_InitStep 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SfcClass_InitStep *pCmd;
  } CltChCmd_SfcClass_InitStep;

typedef struct CltChCmd_SfcClass_InternalVarHolder 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SfcClass_InternalVarHolder *pCmd;
  } CltChCmd_SfcClass_InternalVarHolder;

typedef struct CltChCmd_SfcClass_Step0 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SfcClass_Step0 *pCmd;
  } CltChCmd_SfcClass_Step0;

typedef struct CltChCmd_SfcClass_Transition0 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SfcClass_Transition0 *pCmd;
  } CltChCmd_SfcClass_Transition0;

typedef struct CltChCmd_SfcClass_Transition1 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SfcClass_Transition1 *pCmd;
  } CltChCmd_SfcClass_Transition1;

typedef struct CltChCmd_SigCLib 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    SigCLib *pCmd;
  } CltChCmd_SigCLib;

typedef struct CltChCmd_String 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    String *pCmd;
  } CltChCmd_String;

typedef struct CltChCmd_StringInternal 
  {
    struct SvrChCmd_UDINT *pCh;
    UDINT dData;
    StringInternal *pCmd;
  } CltChCmd_StringInternal;

typedef struct SvrChCmd_IO_State 
  {
    CMDMETH *pMeth;
    IO_State dData;
    SVRDSC *pDsc;
  } SvrChCmd_IO_State;

typedef struct CltChCmd_SyncCall 
  {
    struct SvrChCmd_IO_State *pCh;
    IO_State dData;
    SyncCall *pCmd;
  } CltChCmd_SyncCall;

typedef struct CltChCmd_System 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    System *pCmd;
  } CltChCmd_System;

typedef struct CltChCmd_t_e_VaranErrors 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    SVRCHCMD *pCmd;
  } CltChCmd_t_e_VaranErrors;

typedef struct CltChCmd_Varan_Base 
  {
    struct SvrChCmd_t_e_VaranErrors *pCh;
    t_e_VaranErrors dData;
    Varan_Base *pCmd;
  } CltChCmd_Varan_Base;

typedef struct CltChCmd_VaranManager_Base 
  {
    struct SvrChCmd_DINT *pCh;
    DINT dData;
    VaranManager_Base *pCmd;
  } CltChCmd_VaranManager_Base;

typedef struct CltChCmd_WatchdogDias 
  {
    struct SvrChCmd_IO_State *pCh;
    IO_State dData;
    WatchdogDias *pCmd;
  } CltChCmd_WatchdogDias;

typedef struct SvrCh__FSM_UDP_ERROR_PTofCls_SafetyUDP 
  {
    CHMETH *pMeth;
    _FSM_UDP_ERROR dData;
    SVRDSC *pDsc;
  } SvrCh__FSM_UDP_ERROR_PTofCls_SafetyUDP;

typedef struct SvrCh__FSM_UDP_USER_PTofCls_SafetyUDP 
  {
    CHMETH *pMeth;
    _FSM_UDP_USER dData;
    SVRDSC *pDsc;
  } SvrCh__FSM_UDP_USER_PTofCls_SafetyUDP;

typedef struct SvrCh__INITSTEPS_PTofCls_SafetyUDP 
  {
    CHMETH *pMeth;
    _INITSTEPS dData;
    SVRDSC *pDsc;
  } SvrCh__INITSTEPS_PTofCls_SafetyUDP;

typedef struct SvrCh_BDINT 
  {
    CHMETH *pMeth;
    BDINT dData;
    SVRDSC *pDsc;
  } SvrCh_BDINT;

typedef struct SvrCh_SafetyConfigStateType 
  {
    CHMETH *pMeth;
    SafetyConfigStateType dData;
    SVRDSC *pDsc;
  } SvrCh_SafetyConfigStateType;

typedef struct SvrCh_t_e_VaranErrors 
  {
    CHMETH *pMeth;
    t_e_VaranErrors dData;
    SVRDSC *pDsc;
  } SvrCh_t_e_VaranErrors;

typedef struct SvrCh_t_FaultFlagSvr_PTofCls_SDCIDevice 
  {
    CHMETH *pMeth;
    t_FaultFlagSvr dData;
    SVRDSC *pDsc;
  } SvrCh_t_FaultFlagSvr_PTofCls_SDCIDevice;

typedef struct SvrCh_t_s_SdiasFWStateStandard_PTofCls_SdiasBase 
  {
    CHMETH *pMeth;
    t_s_SdiasFWStateStandard dData;
    SVRDSC *pDsc;
  } SvrCh_t_s_SdiasFWStateStandard_PTofCls_SdiasBase;

typedef struct SvrCh_t_SDCIPortStateBits_PTofCls_SdiasSDCIMaster 
  {
    CHMETH *pMeth;
    t_SDCIPortStateBits dData;
    SVRDSC *pDsc;
  } SvrCh_t_SDCIPortStateBits_PTofCls_SdiasSDCIMaster;

typedef struct SvrCh_TErrorSvr_PTofCls_LseEasy 
  {
    CHMETH *pMeth;
    TErrorSvr dData;
    SVRDSC *pDsc;
  } SvrCh_TErrorSvr_PTofCls_LseEasy;

typedef struct SvrCh_TIME_LSL 
  {
    CHMETH *pMeth;
    TIME_LSL dData;
    SVRDSC *pDsc;
  } SvrCh_TIME_LSL;

typedef struct SvrCh_TStateSvr_PTofCls_LseEasy 
  {
    CHMETH *pMeth;
    TStateSvr dData;
    SVRDSC *pDsc;
  } SvrCh_TStateSvr_PTofCls_LseEasy;

typedef struct SvrChCmd_BDINT 
  {
    CMDMETH *pMeth;
    BDINT dData;
    SVRDSC *pDsc;
  } SvrChCmd_BDINT;

typedef struct SvrChCmd_DATE_LSL 
  {
    CMDMETH *pMeth;
    DATE_LSL dData;
    SVRDSC *pDsc;
  } SvrChCmd_DATE_LSL;

typedef struct SvrChCmd_iprStates 
  {
    CMDMETH *pMeth;
    iprStates dData;
    SVRDSC *pDsc;
  } SvrChCmd_iprStates;

